### ISSUE TITLE
Allow specifying the hostname/IP to use for the HTTP server base URI

### ISSUE THREAD

**Issue by MatthiasBach** [mesosphere/cassandra-mesos#113]
I am working on a set-up where the hostname of the machine does not resolve to the IP via which the machine can be reached by the Mesos slaves and masters. Thus, Cassandra-Mesos binds its HTTP server to the -- for my set-up -- wrong IP and fails to receive resource grants. And even if it would receive resources, slaves would not be able to download Java their requirements. I would thus suggest to use the variable `API_HOST` via which one can configure the IP to bind to. If unset, fall back to the existing solution of using `InetAddress.getLocalHost()` should be performed.

**Comment by MatthiasBach** [comment]
Just as a bit of information for anybody having similar issues. What is requested in this issue will only fix the binding of the API. You might still get connection errors from the Mesos master. In this case you will have also have to set `LIBPROCESS_IP` to make the Mesos client code use the correct IP.

**Comment by BenWhitehead** [comment]
@MatthiasBach Can you outline what your networking setup looks like so that we and better understand why the current approach fails?  

The current implementation has successfully been ran on clusters with multiple NICs on different subnets so I'd like to understand the differences here.

I'm hesitant to add a parameter for this sort of thing, because there are many many scenarios in which having params like this end up leaking into larger configurations issues. `LIBPROCESS_IP` is one of these, many many people jump to manually configuring that field rather than cleaning up (what is usually a minor issue) the network config.

**Comment by MatthiasBach** [comment]
Thanks, `LIBPROCESS_IP` really is an annoying beast.
In our set-up we have dedicated management and service interfaces. The hostname as reported by `hostname` resolves to the management interface, as a host might be reachable via multiple hostnames on the service interface.
Thus, the REST API will bind to this interface. However, other hosts in the cluster will only be able to access the service interface. As they will have to use the REST API to resolve the _current nodes_ I need a way of binding the API to this interface..

**Comment by BenWhitehead** [comment]
Thanks for the info @MatthiasBach.

I just merged #114 that allows for the configuration of the host for the http server by specifying the `HOST` environment variable.  This is something that you get for free if you are running the scheduler via marathon like we do for DCOS.

Does this allow the level of configuration you need? A new marathon.json including this merge can be found [here](https://teamcity.mesosphere.io/repository/download/Oss_Mesos_Cassandra_CassandraFramework/24372:id/marathon.json).

**Comment by MatthiasBach** [comment]
Yes, this should work. Thanks!
