### ISSUE TITLE
Configuration in Zookeeper seems to overwrite Framework Runtime Configuration in environment variables

### ISSUE THREAD

**Issue by flosell** [mesosphere/cassandra-mesos#122]
When initially starting the framework, we did not set the `CASSANDRA_FRAMEWORK_MESOS_ROLE` environment variable.  When we later tried to change this, we noticed the framework was still using the default `*`-role to reserve resources. 
After we deleted the framework-state in zookeeper, the role configured in the environment-variable was used.  

Is this behaviour intentional? If yes, maybe this should be documented more clearly. We would have assumed that configuration in environment variables would be applied in any case.

**Comment by BenWhitehead** [comment]
Hi @flosell,

This behavior is intended.  The majority of the environment variables are actually used for bootstrapping the framework not for ongoing runtime configuration.

This is important for multiple reasons. For example we want to make sure that all configuration is accurately preserved across restarts of the framework.  The specific example you mentioned with role is a great one, when a framework registers with a role it will only be offered resources for that role. If one of the tasks for cassandra were running and then died, the framework may never be able to regain access to those resources to try and restart the task.  This specific scenario is actually present with mesos it self as well, when a framework registers all registration information has to be consistent across restarts. If it is not consistent, it is considered an error condition and mesos will refuse to all the framework to re-register.

Another example has to do with the size of the tasks, in a near release of mesos a new feature will be provided called Dynamic Reservations. This new feature will allow the cassandra framework to reserve all the resources necessary to run all its tasks so that if one of the tasks fails cassandra will be ensured to receive the resources rather than being offered back to the general cluster. In order for the reservation the size needs to be known up front and can't change otherwise we could run into a scenario where there won't be enough resources available to run the new tasks (say if the tasks cpu count increased).

Another reason for this restriction is to make sure that the framework is away of any mutations to configuration that take place.  After the bootstrapping takes place any mutations that are allowed are done through the REST Api, this ensures that the framework can correctly respond to the intended mutations rather than configuration values being changed out from underneath it.

If there are specific configurations values you'd like to change it's would be great to hear what they are so we can evaluate and work them into the REST Api so that they're available for you.

**Comment by flosell** [comment]
Hi, thanks for the detailed explanation!
I added something to the README that might have made it easier for me to understand what was happening. 

I don't think we need a REST API for those things, new users just need to be aware the configuration works like this.

**Comment by BenWhitehead** [comment]
Thanks for the PR.
