### ISSUE TITLE
Invalid cluster name specified in the cassandra.yaml

### ISSUE THREAD

**Issue by vimvim** [mesosphere/cassandra-mesos#138]
Executor adds "cassandra." prefix to the cluster name specified in the marathon.json

---------------------------------------------------------------------------------------------------------------------------
marathon.json:
  "env": {
   ....
    "CASSANDRA_CLUSTER_NAME": "ClusterName1",

---------------------------------------------------------------------------------------------------------------------------
cassandra.yaml ( on the worker node ):
....
cluster_name: cassandra.ClusterName1
...
---------------------------------------------------------------------------------------------------------------------------

**Comment by elingg** [comment]
I believe this is as expected. Is it causing any issues?

**Comment by vimvim** [comment]
Yes, this problem is cause serious configuration issue because we unable to setup replication with the external Cassandra cluster ( native Cassandra - without cassandra-mesos ). External cluster has name "ClusterName1" ( not real name - only for example). This is production cluster,so we unable to change this name to another. At the same time we can't specify this cluster name for new cassandra-mesos cluster ( cassandra-mesos adds "cassandra." prefix )

**Comment by kensipe** [comment]
we had an engineering discussion on this today... there is framework work needed in order to provide this ability and I've added a task internally to be scheduled.  We are open to a PR if you would like to accelerate that.   If you do work on this, it is important to provide previous naming for clusters from the previous version in addition to adding new behavior to new clusters.

**Comment by elingg** [comment]
@BenWhitehead created a PR for this, thanks! With the latest master code it will work, @vimvim
