### ISSUE TITLE
Error in startup of framework

### ISSUE THREAD

**Issue by exnerd** [mesosphere/cassandra-mesos#88]
Hi,

I tried the latest version of the cassandra-mesos framework. When I start the job with a marathon job I got following message in the cassandra-mesos.log : io.mesosphere.mesos.util.ProtoUtils$RuntimeInvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: healthCheckIntervalSeconds, defaultConfigRole 

I tried to add  "CASSANDRA_HEALTH_CHECK_INTERVAL_SECONDS" : "60" and "CASSANDRA_FRAMEWORK_MESOS_ROLE": "*" environment variable to the marathon json file, but that didn't changed the behaviour.

Any clue what the issue could be ?

Regards,

Ben

**Comment by exnerd** [comment]
Ok, found the solution. I removed the cassandra-mesos tree in zookeeper from a previous build. And everything works fine.

Still have a question, though. In the marathon.json file the uri contains the distribution tar.gz. But how does the jre finds the necessary jars if they are in the subdir cassandra-mesos-dist-0.1.0.SNAPSHOT/ ?
I had to unpack the dist tar.gz  otherwise I got the following error

    java.lang.IllegalArgumentException: Unable to read specified resource: /tmp/mesos/slaves/20150319-070939-2618897857-5050-2322-S0/frameworks/20150127-145729-2937664961-5050-16500-0000/executors/cassandra_dev-test.abda8209-ddc4-11e4-bc5a-52540018521d/runs/f028ceeb-ad54-410f-a935-0aa6a5e482f0/apache-cassandra-2.1.4-bin.tar.gz

**Comment by BenWhitehead** [comment]
Hi @exnerd,

Can you provide a larger stack track for when you encountered the exception about missing required fields?

There are default values set in the main so that if they're not passed in the environment they should still be there.

Correct, right now we don't have any means of allowing configuration to change after the initial start of the framework.  This is a limitation that will hopefully be removed in the future. 

In the marathon.json we specify the full URL to the jre and bundled tar.gz.  When marathon launches the task on mesos, mesos will download the two tars and extract them into the current directory. When we create the bundle we use well known names for the JRE, apache bundle and executor jar so that they can then be served to slaves to run tasks. You shouldn't have had to extract things yourself.

Can you paste the marathon.json here that you tried out so that I can try and help track down the issue?

**Comment by BenWhitehead** [comment]
Closing as I've not been able to reproduce this.
