### ISSUE TITLE
Error building Cassandra-mesos-dist 

### ISSUE THREAD

**Issue by samklr** [mesosphere/cassandra-mesos#89]
Hi,
I tried to build the project but there seems to be an issue when maven tries to download the bnary at https://downloads.mesosphere.io/cassandra-mesos/cassandra/apache-casandra-2.1.4-bin.tar.gz in the cassandra-mesos-dist module.

**Comment by BenWhitehead** [comment]
It looks like you have a typo in the URL you've pasted. It should be

```
actual: https://downloads.mesosphere.io/cassandra-mesos/cassandra/apache-casandra-2.1.4-bin.tar.gz
should: https://downloads.mesosphere.io/cassandra-mesos/cassandra/apache-cassandra-2.1.4-bin.tar.gz
```

Rather than building it yourself, you can run the framework via marathon using the marathon json from the latest build [here](https://teamcity.mesosphere.io/guestAuth/repository/download/Oss_Mesos_Cassandra_CassandraFramework/.lastSuccessful/marathon.json)

If you don't want to run it via marathon (I would highly recommend you do) you can get the url for the latest build from the marathon json linked above.

**Comment by samklr** [comment]
Oh yeah right. Managed to run it through marathon eventually using marathon.json. Thx

**Comment by BenWhitehead** [comment]
Sure, happy to help.

Thanks for raising the issue, we've seen issues with other resources in this public s3 bucket for other projects too, so there is a possibility there was service blip with s3.
